title: LLC notes
description: Visual study notes with flow diagrams and brief explanation
theme: just-the-docs

# URL setup
url: "https://d33pto3.github.io"
baseurl: "/llc-notes"

# Navigation order
nav_sort: case_insensitive

# Enable search
search_order: true

# Optional: color scheme
color_scheme: dark

favicon: /assets/images/favicons/favicon.ico

# Footer customization
aux_links:
  "View on Github": "https://github.com/d33pto3/llc-notes"
  "Template Repository":
    - //github.com/d33pto3/llc-notes
